kumuluzee:
  name: badmiton-app-users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BadmintonAppUsersDS
      connection-url: ${{ secrets.POSTGRES_URL }}
      username: ${{ secrets.POSTGRES_NAME }}
      password: ${{ secrets.POSTGRES_PASS }}
rest-properties:
  maintenance-mode: false
