kumuluzee:
  name: badmiton-app-users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BadmintonAppUsersDS
      connection-url: jdbc:postgresql://database-1.ctekqcytce4y.eu-central-1.rds.amazonaws.com/badminton
      username: postgres
      password: postgres

  config:
    start-retry-delay-ms: 200
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://20.85.253.39:2379

  discovery:
    cluster: 1
    etcd:
      hosts: http://20.85.253.39:2379
      ttl: 30
      ping-interval: 5
rest-properties:
  maintenance-mode: false
  broken: false
  userDiscovery: true