kumuluzee:
  name: badmiton-app-users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BadmintonAppUsersDS
      connection-url: jdbc:postgresql://database-1.ctekqcytce4y.eu-central-1.rds.amazonaws.com/badminton
      username: postgres
      password: postgres

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                              <Configuration name="comments">
                                  <Appenders>
                                      <Console name="console" target="SYSTEM_OUT">
                                          <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                      </Console>
                                      <Socket name="logstash" host="9e7e196e-585e-42ec-a003-b75a227be7d5-ls.logit.io"
                                      port="13921" protocol="udp">
                                          <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                      </Socket>
                                  </Appenders>
                                  <Loggers>
                                      <!-- Default logger -->
                                      <Root level="all">
                                          <AppenderRef ref="console" level="info" />
                                          <AppenderRef ref="logstash" level="info" />
                                      </Root>
                                  </Loggers>
                              </Configuration>'

  config:
    start-retry-delay-ms: 200
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://20.85.253.39:2379

  discovery:
    cluster: 1
    etcd:
      hosts: http://20.85.253.39:2379
      ttl: 30
      ping-interval: 5
rest-properties:
  maintenance-mode: false
  broken: false
  userDiscovery: true